[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="footerTextHTML" type="java.lang.String" --]
[#-- @ftlvariable name="paths" type="jetbrains.coverage.report.impl.html.GeneratorPaths" --]
[#-- @ftlvariable name="generateDate" type="java.util.Date" --]
[#-- @ftlvariable name="resources" type="freemarker.ext.beans.ResourceBundleModel"  --]
[#-- @ftlvariable name="statsCalculator" type="jetbrains.coverage.report.StatisticsCalculator" --]
[#-- @ftlvariable name="sort_option_sort_by_name" type="jetbrains.coverage.report.impl.html.SortOption" --]
[#-- @ftlvariable name="sort_option_none" type="jetbrains.coverage.report.impl.html.SortOption" --]
[#-- @ftlvariable name="include_modules" type="java.lang.Boolean" --]
[#-- @ftlvariable name="reportTitle" type="java.lang.String" --]
